export default {
  // stage
  STAGE_MOUSE_ENTER: 'STAGE_MOUSE_ENTER',
  STAGE_MOUSE_MOVE: 'STAGE_MOUSE_MOVE',
  STAGE_MOUSE_LEAVE: 'STAGE_MOUSE_LEAVE',
  STAGE_MOUSE_DOWN: 'STAGE_MOUSE_DOWN',
  STAGE_CLICK: 'STAGE_CLICK',
  STAGE_MOUSE_UP: 'STAGE_MOUSE_UP',
  STAGE_CONTEXT_MENU: 'STAGE_CONTEXT_MENU',
  // shape
  ELEMENT_MOUSE_ENTER: 'ELEMENT_MOUSE_ENTER',
  ELEMENT_MOUSE_MOVE: 'ELEMENT_MOUSE_MOVE',
  ELEMENT_MOUSE_LEAVE: 'ELEMENT_MOUSE_LEAVE',
  ELEMENT_MOUSE_DOWN: 'ELEMENT_MOUSE_DOWN',
  ELEMENT_CLICK: 'ELEMENT_CLICK',
  ELEMENT_MOUSE_UP: 'ELEMENT_MOUSE_UP',

}